# Generated by Django 4.0.4 on 2022-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
