# Generated by Django 4.0.4 on 2022-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('data_number', models.IntegerField(default=0)),
                ('data_month', models.IntegerField(default=0)),
                ('data_year', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
