# Generated by Django 4.0.4 on 2022-06-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'car'},
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
