# Generated by Django 4.0.4 on 2022-06-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_cars_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(default='black', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='mark',
            field=models.CharField(choices=[('bmw', 'bmw'), ('mercedes', 'mercedes'), ('toyota', 'toyota'), ('audi', 'audi')], default='bmw', max_length=10),
        ),
    ]
