# Generated by Django 4.0.4 on 2022-06-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_carcolor_alter_cars_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.carcolor', verbose_name='color'),
        ),
    ]
