# Generated by Django 4.0.4 on 2022-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_cars_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcolor',
            name='color_name',
            field=models.CharField(max_length=12),
        ),
    ]
