# Generated by Django 4.0.4 on 2022-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_alter_cars_mark_alter_cars_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
